const recruitersData = [
  {
    title: "Tech & Product Companies",
    icon: <Cpu size={20} strokeWidth={2.5} />,
    companies: [
      { name: "Adobe", initial: "A" },
      { name: "Amazon", initial: "A" },
      { name: "Airtel", initial: "A" },
      { name: "Alphabet (Google)", initial: "G" },
      { name: "Apple (Via Partners)", initial: "A" },
      { name: "Blue Star", initial: "B" },
      { name: "Cisco Systems", initial: "C" },
      { name: "Ericsson", initial: "E" },
      { name: "Flipkart", initial: "F" },
      { name: "GreyOrange Robotics", initial: "G" },
      { name: "Havells", initial: "H" },
      { name: "HCL", initial: "H" },
      { name: "Honda Group", initial: "H" },
      { name: "Jio", initial: "J" },
      { name: "Josh Technology", initial: "J" },
      { name: "Juniper Networks", initial: "J" },
      { name: "Kohler", initial: "K" },
      { name: "Lenskart", initial: "L" },
      { name: "MapmyIndia", initial: "M" },
      { name: "Media.net", initial: "M" },
      { name: "Mitsubishi Electric", initial: "M" },
      { name: "Relaxo Footwears", initial: "R" },
      { name: "Samsung India", initial: "S" },
      { name: "Siemens", initial: "S" },
      { name: "STMicroelectronics", initial: "S" },
      { name: "Swiggy Instamart", initial: "S" },
      { name: "Tata Power", initial: "T" },
      { name: "TVS Motor", initial: "T" },
      { name: "Uber", initial: "U" },
      { name: "Vivo Mobile", initial: "V" },
      { name: "Whirlpool India", initial: "W" },
      { name: "Walmart", initial: "W" },
      { name: "Yamaha Motors", initial: "Y" }
    ],
  },
  {
    title: "IT Services & Consulting",
    icon: <Server size={20} strokeWidth={2.5} />,
    companies: [
      { name: "Accenture", initial: "A" },
      { name: "Atos Syntel", initial: "A" },
      { name: "Birlasoft", initial: "B" },
      { name: "Capgemini", initial: "C" },
      { name: "Cognizant", initial: "C" },
      { name: "Coforge", initial: "C" },
      { name: "EXL", initial: "E" },
      { name: "Gemini Solutions", initial: "G" },
      { name: "HCL Tech", initial: "H" },
      { name: "IBM (via partners)", initial: "I" },
      { name: "Infosys", initial: "I" },
      { name: "KPMG India", initial: "K" },
      { name: "LTIMindtree", initial: "L" },
      { name: "Mphasis (via partners)", initial: "M" },
      { name: "Nagarro", initial: "N" },
      { name: "Oracle (via partners)", initial: "O" },
      { name: "PureSoftware", initial: "P" },
      { name: "SAP (via partners)", initial: "S" },
      { name: "Tech Mahindra", initial: "T" },
      { name: "TCS", initial: "T" },
      { name: "Wipro", initial: "W" },
      { name: "Zensar Technologies", initial: "Z" }
    ],
  },
  {
    title: "BFSI & Financial Services",
    icon: <CreditCard size={20} strokeWidth={2.5} />,
    companies: [
      { name: "Axis Bank", initial: "A" },
      { name: "BNY Mellon", initial: "B" },
      { name: "Goldman Sachs", initial: "G" },
      { name: "HDFC Bank", initial: "H" },
      { name: "ICICI Bank", initial: "I" },
      { name: "JP Morgan Chase", initial: "J" },
      { name: "Morgan Stanley", initial: "M" },
      { name: "Principal Financial", initial: "P" }
    ],
  },
  {
    title: "Engineering & Manufacturing",
    icon: <Factory size={20} strokeWidth={2.5} />,
    companies: [
      { name: "ABB Group", initial: "A" },
      { name: "Ashok Leyland", initial: "A" },
      { name: "Berger Paints", initial: "B" },
      { name: "Bosch", initial: "B" },
      { name: "Dabur India", initial: "D" },
      { name: "Denso India", initial: "D" },
      { name: "DLF Group", initial: "D" },
      { name: "Escorts Kubota", initial: "E" },
      { name: "GAIL India", initial: "G" },
      { name: "GKN Driveline", initial: "G" },
      { name: "Haier Appliances", initial: "H" },
      { name: "Hindware", initial: "H" },
      { name: "JCB India", initial: "J" },
      { name: "Jindal Steel & Power", initial: "J" },
      { name: "JSW Group", initial: "J" },
      { name: "Lumax", initial: "L" },
      { name: "Mahle Anand", initial: "M" },
      { name: "Motherson Group", initial: "M" },
      { name: "Orient Electric", initial: "O" },
      { name: "Schneider Electric", initial: "S" },
      { name: "Swaraj Tractors", initial: "S" },
      { name: "Triumph Motorcycles", initial: "T" },
      { name: "UNO Minda", initial: "U" }
    ],
  },
  {
    title: "Healthcare & Pharma",
    icon: <Heart size={20} strokeWidth={2.5} />,
    companies: [
      { name: "Apollo Hospitals", initial: "A" },
      { name: "Dabur India", initial: "D" },
      { name: "Medtronic India", initial: "M" },
      { name: "Yashoda Group", initial: "Y" }
    ],
  },
  {
    title: "Automotive & Transportation",
    icon: <Car size={20} strokeWidth={2.5} />,
    companies: [
      { name: "Ashok Leyland", initial: "A" },
      { name: "Hero Motors", initial: "H" },
      { name: "Honda Group", initial: "H" },
      { name: "JBM Auto", initial: "J" },
      { name: "Maruti Suzuki", initial: "M" },
      { name: "TVS Motor", initial: "T" },
      { name: "Yamaha Motors", initial: "Y" }
    ],
  },
  {
    title: "Telecom & Infrastructure",
    icon: <Wifi size={20} strokeWidth={2.5} />,
    companies: [
      { name: "Airtel", initial: "A" },
      { name: "Ciena", initial: "C" },
      { name: "Ericsson", initial: "E" },
      { name: "HFCL", initial: "H" },
      { name: "Jio", initial: "J" },
      { name: "Mavenir", initial: "M" },
      { name: "Nokia (via partners)", initial: "N" },
      { name: "Vodafone Idea", initial: "V" }
    ],
  },
  {
    title: "Consulting & Research",
    icon: <BarChart size={20} strokeWidth={2.5} />,
    companies: [
      { name: "Deloitte (via partners)", initial: "D" },
      { name: "EY (via partners)", initial: "E" },
      { name: "KPMG", initial: "K" },
      { name: "McKinsey (via partners)", initial: "M" },
      { name: "PwC (via partners)", initial: "P" }
    ],
  },
  {
    title: "Media & Entertainment",
    icon: <Tv size={20} strokeWidth={2.5} />,
    companies: [
      { name: "ABP Network", initial: "A" },
      { name: "Bharat24", initial: "B" },
      { name: "India Today Group", initial: "I" },
      { name: "Times Network", initial: "T" },
      { name: "TV9 Bharatvarsh", initial: "T" },
      { name: "Zee Media", initial: "Z" }
    ],
  },
  {
    title: "Government & PSU",
    icon: <Building size={20} strokeWidth={2.5} />,
    companies: [
      { name: "C-DAC", initial: "C" },
      { name: "C-DOT", initial: "C" },
      { name: "DFCCIL", initial: "D" },
      { name: "DRDO (TBRL)", initial: "D" },
      { name: "Indian Oil (R&D)", initial: "I" },
      { name: "ISRO", initial: "I" },
      { name: "NBCC India", initial: "N" },
      { name: "NCC Limited", initial: "N" },
      { name: "RITES India", initial: "R" }
    ],
  },
  {
    title: "Startups & Emerging Tech",
    icon: <Rocket size={20} strokeWidth={2.5} />,
    companies: [
      { name: "Addverb Technologies", initial: "A" },
      { name: "Ather Energy (via partners)", initial: "A" },
      { name: "Cred (via CredResolve)", initial: "C" },
      { name: "Digit Insurance (via partners)", initial: "D" },
      { name: "Dream11 (via partners)", initial: "D" },
      { name: "Freshworks (via partners)", initial: "F" },
      { name: "GripInvest", initial: "G" },
      { name: "Innovaccer", initial: "I" },
      { name: "Mobiurja Innovation", initial: "M" },
      { name: "Ola (via partners)", initial: "O" },
      { name: "Paytm (via partners)", initial: "P" },
      { name: "PharmEasy (via partners)", initial: "P" },
      { name: "Rupeek Fintech", initial: "R" },
      { name: "Unacademy (via partners)", initial: "U" },
      { name: "UpGrad (via partners)", initial: "U" },
      { name: "Yellow.ai", initial: "Y" },
      { name: "ZoloStays", initial: "Z" }
    ],
  }
];